/*
 * This file was automatically generated by EvoSuite
 * Mon May 15 17:07:46 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.Appt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true,separateClassLoader = true)
public class Appt_ESTest extends Appt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 1, 1, (String) null, (String) null);
      String string0 = appt0.toString();
      assertNotNull(string0);
      assertEquals("\t1/1/1 at 1:1am ,, \n", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 8, "&l'p<?LX4", "&l'p<?LX4");
      boolean boolean0 = appt0.getValid();
      assertEquals("&l'p<?LX4", appt0.getDescription());
      assertEquals(11, appt0.getStartMonth());
      assertEquals(11, appt0.getStartMinute());
      assertEquals(11, appt0.getStartDay());
      assertTrue(boolean0);
      assertEquals("&l'p<?LX4", appt0.getTitle());
      assertEquals(8, appt0.getStartYear());
      assertEquals(11, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, 23, 23, "", "");
      appt0.getTitle();
      assertEquals(23, appt0.getStartYear());
      assertEquals(23, appt0.getStartHour());
      assertEquals(23, appt0.getStartMinute());
      assertEquals(23, appt0.getStartMonth());
      assertEquals(23, appt0.getStartDay());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Appt appt0 = new Appt((-1165), 23, (-619), (-1165), 0, "", "H6*Td..okNyTkD");
      int int0 = appt0.getStartYear();
      assertEquals(0, int0);
      assertEquals("", appt0.getTitle());
      assertEquals(-1165, appt0.getStartMonth());
      assertEquals("H6*Td..okNyTkD", appt0.getDescription());
      assertEquals(23, appt0.getStartMinute());
      assertEquals(-1165, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(-619, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Appt appt0 = new Appt(603, 603, 940, (-2371), (-1444), "", "");
      int int0 = appt0.getStartYear();
      assertEquals(603, appt0.getStartHour());
      assertEquals(-2371, appt0.getStartMonth());
      assertEquals(603, appt0.getStartMinute());
      assertEquals(940, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals((-1444), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 23, 0, 0, "+vU:8kZDT_!Wl/QJ", "+vU:8kZDT_!Wl/QJ");
      int int0 = appt0.getStartMonth();
      assertFalse(appt0.getValid());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartYear());
      assertEquals("+vU:8kZDT_!Wl/QJ", appt0.getDescription());
      assertEquals(23, appt0.getStartDay());
      assertEquals(0, appt0.getStartHour());
      assertEquals("+vU:8kZDT_!Wl/QJ", appt0.getTitle());
      assertEquals(0, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Appt appt0 = new Appt((-1165), 23, (-619), (-1165), 0, "", "H6*Td..okNyTkD");
      int int0 = appt0.getStartMonth();
      assertFalse(appt0.getValid());
      assertEquals(-1165, appt0.getStartHour());
      assertEquals(0, appt0.getStartYear());
      assertEquals(-619, appt0.getStartDay());
      assertEquals("", appt0.getTitle());
      assertEquals(23, appt0.getStartMinute());
      assertEquals("H6*Td..okNyTkD", appt0.getDescription());
      assertEquals((-1165), int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 8, "&l'p<?LX4", "&l'p<?LX4");
      int int0 = appt0.getStartMinute();
      assertTrue(appt0.getValid());
      assertEquals(11, appt0.getStartDay());
      assertEquals(11, appt0.getStartMonth());
      assertEquals("&l'p<?LX4", appt0.getTitle());
      assertEquals(11, int0);
      assertEquals(8, appt0.getStartYear());
      assertEquals(11, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Appt appt0 = new Appt(0, (-524), (-524), 0, 0, "+,a*AMqcqunU83l", "");
      int int0 = appt0.getStartMinute();
      assertEquals(-524, appt0.getStartDay());
      assertEquals("+,a*AMqcqunU83l", appt0.getTitle());
      assertEquals("", appt0.getDescription());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(0, appt0.getStartHour());
      assertEquals((-524), int0);
      assertEquals(0, appt0.getStartYear());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Appt appt0 = new Appt(880, 59, 991, 880, 0, "\t", "Nb)c|ae*&LJsq8B");
      int int0 = appt0.getStartHour();
      assertEquals(0, appt0.getStartYear());
      assertEquals("Nb)c|ae*&LJsq8B", appt0.getDescription());
      assertEquals("\t", appt0.getTitle());
      assertEquals(59, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals(880, int0);
      assertEquals(880, appt0.getStartMonth());
      assertEquals(991, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Appt appt0 = new Appt(533, 533, 533, (-1025), 533, (String) null, (String) null);
      String string0 = appt0.getDescription();
      assertFalse(appt0.getValid());
      assertEquals(533, appt0.getStartYear());
      assertEquals(-1025, appt0.getStartMonth());
      assertEquals(533, appt0.getStartHour());
      assertEquals(533, appt0.getStartMinute());
      assertEquals(533, appt0.getStartDay());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Appt appt0 = new Appt((-1267), (-1267), (-1267), (-1267), (-1267), "\n", "AllFieldsNull");
      appt0.setDescription("AllFieldsNull");
      assertEquals(-1267, appt0.getStartMonth());
      assertEquals(-1267, appt0.getStartYear());
      assertEquals("AllFieldsNull", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals(-1267, appt0.getStartHour());
      assertEquals(-1267, appt0.getStartMinute());
      assertEquals("\n", appt0.getTitle());
      assertEquals(-1267, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Appt appt0 = new Appt((-4334), (-3181), 400, 400, 100, " ,", " ,");
      assertEquals(" ,", appt0.getDescription());

      appt0.setDescription((String) null);
      assertEquals(100, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Appt appt0 = new Appt((-1), 588, 1120, (-604), 6458, " at ", " at ");
      appt0.setTitle(" at ");
      assertEquals(-1, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(1120, appt0.getStartDay());
      assertEquals(" at ", appt0.getTitle());
      assertEquals(-604, appt0.getStartMonth());
      assertEquals(6458, appt0.getStartYear());
      assertEquals(588, appt0.getStartMinute());
      assertEquals(" at ", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 23, 0, 0, "+vU:8kZDT_!Wl/QJ", "+vU:8kZDT_!Wl/QJ");
      assertEquals("+vU:8kZDT_!Wl/QJ", appt0.getTitle());

      appt0.setTitle((String) null);
      assertEquals(23, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Appt appt0 = new Appt((-1307), (-1307), (-1307), (-1307), (-1307), "`2OTaf", "`2OTaf");
      String string0 = appt0.getTitle();
      assertEquals(-1307, appt0.getStartYear());
      assertEquals(-1307, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals("`2OTaf", string0);
      assertEquals(-1307, appt0.getStartMonth());
      assertEquals(-1307, appt0.getStartMinute());
      assertEquals(-1307, appt0.getStartDay());
      assertEquals("`2OTaf", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Appt appt0 = new Appt(0, 59, 0, 4061, 4061, ">24aJ/!", ">24aJ/!");
      int int0 = appt0.getStartDay();
      assertEquals(4061, appt0.getStartYear());
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, int0);
      assertEquals(4061, appt0.getStartMonth());
      assertEquals(">24aJ/!", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals(59, appt0.getStartMinute());
      assertEquals(">24aJ/!", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Appt appt0 = new Appt((-807), 0, 0, 0, 0, "", "");
      boolean boolean0 = appt0.getValid();
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartMinute());
      assertFalse(boolean0);
      assertEquals(-807, appt0.getStartHour());
      assertEquals(0, appt0.getStartDay());
      assertEquals(0, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Appt appt0 = new Appt((-1267), (-1267), (-1267), (-1267), (-1267), "\n", "AllFieldsNull");
      int int0 = appt0.getStartHour();
      assertFalse(appt0.getValid());
      assertEquals(-1267, appt0.getStartDay());
      assertEquals(-1267, appt0.getStartYear());
      assertEquals("AllFieldsNull", appt0.getDescription());
      assertEquals(-1267, appt0.getStartMinute());
      assertEquals(-1267, appt0.getStartMonth());
      assertEquals("\n", appt0.getTitle());
      assertEquals((-1267), int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Appt appt0 = new Appt((-1), 588, 1120, (-604), 6458, " at ", " at ");
      int int0 = appt0.getStartYear();
      assertEquals(-604, appt0.getStartMonth());
      assertEquals(1120, appt0.getStartDay());
      assertEquals(" at ", appt0.getTitle());
      assertEquals(6458, int0);
      assertEquals(-1, appt0.getStartHour());
      assertEquals(588, appt0.getStartMinute());
      assertEquals(" at ", appt0.getDescription());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Appt appt0 = new Appt(508, 0, 0, 1130, (-3079), "[!x9HF#^0%", (String) null);
      int int0 = appt0.getStartMinute();
      assertEquals("[!x9HF#^0%", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals(0, int0);
      assertEquals(1130, appt0.getStartMonth());
      assertEquals(0, appt0.getStartDay());
      assertEquals("", appt0.getDescription());
      assertEquals(-3079, appt0.getStartYear());
      assertEquals(508, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "InvalidFieldValue", "InvalidFieldValue");
      String string0 = appt0.getDescription();
      assertEquals(11, appt0.getStartHour());
      assertEquals(11, appt0.getStartYear());
      assertEquals(11, appt0.getStartMinute());
      assertEquals("InvalidFieldValue", string0);
      assertEquals(11, appt0.getStartDay());
      assertTrue(appt0.getValid());
      assertEquals("InvalidFieldValue", appt0.getTitle());
      assertEquals(11, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "InvalidFieldValue", "InvalidFieldValue");
      int int0 = appt0.getStartMonth();
      assertEquals(11, int0);
      assertEquals("InvalidFieldValue", appt0.getDescription());
      assertTrue(appt0.getValid());
      assertEquals(11, appt0.getStartMinute());
      assertEquals("InvalidFieldValue", appt0.getTitle());
      assertEquals(11, appt0.getStartYear());
      assertEquals(11, appt0.getStartHour());
      assertEquals(11, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 12, "", "");
      String string0 = appt0.toString();
      assertEquals("\t12/12/12 at 12:12pm ,, \n", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Appt appt0 = new Appt(508, 0, 0, 1130, (-3079), "[!x9HF#^0%", (String) null);
      String string0 = appt0.toString();
      assertEquals("[!x9HF#^0%", appt0.getTitle());
      assertNull(string0);
      assertEquals(1130, appt0.getStartMonth());
      assertEquals(0, appt0.getStartDay());
      assertEquals(508, appt0.getStartHour());
      assertEquals(0, appt0.getStartMinute());
      assertEquals("", appt0.getDescription());
      assertEquals(-3079, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Appt appt0 = new Appt(57, 57, 57, 6, 0, (String) null, "o5Cv:k1b`!VM9eoL!");
      appt0.setStartDay((-230));
      int int0 = appt0.getStartDay();
      assertEquals((-230), int0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Appt appt0 = new Appt(508, 0, 0, 1130, (-3079), "[!x9HF#^0%", (String) null);
      appt0.setStartDay(31);
      appt0.setStartHour(0);
      appt0.setStartMonth((-3061));
      assertEquals(31, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Appt appt0 = new Appt(0, 59, 0, 4061, 4061, ">24aJ/!", ">24aJ/!");
      appt0.setStartDay(3490);
      int int0 = appt0.getStartDay();
      assertEquals(3490, int0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Appt appt0 = new Appt(0, (-1594), 0, 0, 0, "pm", "pm");
      int int0 = appt0.getStartHour();
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(0, appt0.getStartDay());
      assertEquals("pm", appt0.getTitle());
      assertEquals("pm", appt0.getDescription());
      assertEquals(-1594, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Appt appt0 = new Appt(508, 0, 0, 1130, (-3079), "[!x9HF#^0%", (String) null);
      appt0.setStartMinute(1130);
      assertEquals(508, appt0.getStartHour());

      appt0.setStartHour(0);
      assertEquals(0, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Appt appt0 = new Appt(0, 59, 0, 4061, 4061, ">24aJ/!", ">24aJ/!");
      appt0.setStartYear(1120);
      assertEquals(1120, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "InvalidFieldValue", "InvalidFieldValue");
      String string0 = appt0.toString();
      assertNotNull(string0);
      assertEquals("\t11/11/11 at 11:11am ,InvalidFieldValue, InvalidFieldValue\n", string0);
  }
}
