/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 16 22:55:29 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ArrayIntList_ESTest extends ArrayIntList_ESTest_scaffolding {

  @Test
  public void test00()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList(1);
      // Undeclared exception!
      try { 
        arrayIntList0.ensureCapacity(1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         assertThrownBy("ArrayIntList", e);
      }
  }

  @Test
  public void test01()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList();
      arrayIntList0.remove((-5033));
      arrayIntList0.remove((-5033));
  }

  @Test
  public void test02()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList();
      arrayIntList0.remove(99);
      // Undeclared exception!
      try { 
        arrayIntList0.ensureCapacity(78);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 99
         //
         assertThrownBy("ArrayIntList", e);
      }
  }

  @Test
  public void test03()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList();
      // Undeclared exception!
      try { 
        arrayIntList0.get(430);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 429
         //
         assertThrownBy("ArrayIntList", e);
      }
  }

  @Test
  public void test04()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList();
      // Undeclared exception!
      try { 
        arrayIntList0.copyOf((ArrayIntList) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("ArrayIntList", e);
      }
  }

  @Test
  public void test05()  throws Throwable  {
      ArrayIntList arrayIntList0 = null;
      try {
        arrayIntList0 = new ArrayIntList((-223));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("ArrayIntList", e);
      }
  }

  @Test
  public void test06()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList();
      arrayIntList0.remove(1);
      arrayIntList0.size();
  }

  @Test
  public void test07()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList();
      arrayIntList0.get(45);
  }

  @Test
  public void test08()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList(1075);
      arrayIntList0.ensureCapacity(1);
      assertEquals(100, arrayIntList0.size());
  }

  @Test
  public void test09()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList();
      // Undeclared exception!
      try { 
        arrayIntList0.ensureCapacity(2322);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 99
         //
         assertThrownBy("ArrayIntList", e);
      }
  }

  @Test
  public void test10()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList();
      ArrayIntList arrayIntList1 = new ArrayIntList(1075);
      arrayIntList0.copyOf(arrayIntList1);
      assertEquals(100, arrayIntList0.size());
  }

  @Test
  public void test11()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList();
      // Undeclared exception!
      try { 
        arrayIntList0.copyOf(arrayIntList0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 99
         //
         assertThrownBy("ArrayIntList", e);
      }
  }

  @Test
  public void test12()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList(1399);
      arrayIntList0.add(1399);
      arrayIntList0.add(1399);
      // Undeclared exception!
      try { 
        arrayIntList0.remove(98);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1398
         //
         assertThrownBy("ArrayIntList", e);
      }
  }

  @Test
  public void test13()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList();
      // Undeclared exception!
      try { 
        arrayIntList0.add((-69));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 100
         //
         assertThrownBy("ArrayIntList", e);
      }
  }
}
